### ISSUE TITLE
Dynamically sized  registers

### ISSUE THREAD

**Issue by mlgiraud** [CensoredUsername/dynasm-rs#109]
Hi, i'm really liking this crate so far. I came across the need to dynamically set a registers size, and didn't find anything in the docs so far. I took a look at the parse_reg function, and i believe it shouldn't be that difficult to extend this such that we can also specify the size dynamically?
This could for example look something like this:
```rust
dynasm!(assembler
    ; imul RN(size, register), RN(size2, register2)
);
```
This would make sense for the general purpose registers and maybe for the AVX(1,2,512) registers.

This would make it a lot easier (for me at least) to pick the most appropriate instruction encoding, since the size of the register to use is usually available as some integer (in my case at least).

What is your opinion on this? If you like, i can also propose a PR, if you agree with performing this extension.

EDIT: The same goes for the size of the immediate value by the way. Is it possible to provide this dynamically instead of via the BYTE, WORD, etc. keywords?

**Comment by CensoredUsername** [comment]
Hey! glad to hear this library has been to your liking. I'm assuming we're talking about the x64 assembler here. Unfortunately this is not as simple as it seems. x64 is quite an irregular instruction set, and the issue here is that many of these size combinations do not actually exist, or require a significantly different encoding. On the parser side this would indeed be a simple change, but please take a look at the compiler side. You will find that this is unfortunately anything but simple.

**Comment by mlgiraud** [comment]
But the compiler side doesn't really have to change, does it? Instead of selecting the register by providing Rq(some_reg) or Rd(some_reg) or whatever, we just select it by providing RX(size, some_reg) or something like that. If this selection is invalid, the compiler can still just return an error like before, if the register combination is invalid, or am i overlooking something? As far as i understand the code, the parser simply selects the register that was provided as input and then passes this onto the compiler which then decides if this is a valid encoding or not. Doing this register selection in a different more dynamic way shouldnt require changing the compiler, right?

**Comment by CensoredUsername** [comment]
Based on the edit, you seem to have figured it out. With dynamic registers, the actual encoding gets pushed from compile time to runtime. Which is still simple enough that it's doable.

Doing it with register sizes is significantly more complex. It's better to think of instructions with different operand sizes as different instructions in general. x64 is weird in that it is occasionally generic over operand size (16/32/64 bits), but it isn't always.

**Comment by mlgiraud** [comment]
Im closing this, since it cannot be implementend in a sensible manner imho. The best solution is probably to wrap the dynasm macro into another macro that can do a match on the size and then emit the correct dynasm command.
