### ISSUE TITLE
Mnemonic corrections

### ISSUE THREAD

**Issue by astocko** [CensoredUsername/dynasm-rs#15]
# Broken
**loop** and **in** are broken right now (Rust keywords)

# Additions

- **fistp** - currently only **fist** is present. Should be fistp for /3 and /7
- **fucomip**
- **pshufhw** - **pshuflw** is present, but not the packed high words version
- **vpshufhw** - **vpshuflw** is present, but not the packed high words version

# AMD Only
- **vpermil2** variants were removed by [Intel in 2009](https://software.intel.com/en-us/blogs/2009/01/29/recent-intelr-avx-architectural-changes)

# Malformed encoding formats
| Instruction |  Current  |  Corrected | 
|-------------|-----------|------------| 
| vucomiss    | yoyo/yomd |  ydyd/ydmd | 
| vucomisd    | yoyo/yomq |  yqyq/yqmq | 

# Typos
| Current     |  Corrected   | 
|-------------|--------------| 
| cvtpd2dS    |  cvtpd2ps    | 
| vcvtpd2dS   |  vcvtpd2ps   | 
| palign      |  palignr     | 
| vpalign     |  vpalignr    | 
| pblenddw    |  pblendw     | 
| vpblenddw   |  vpblendw    | 
| vfmaddsuppd |  vfmaddsubpd | 

# Unavailable in NASM
- **monitorx**
- **mwaitx**

**Comment by CensoredUsername** [comment]
I've fixed the broken instructions, additions, malformatted instruction formats and typos in b96da53. For now the AMD only/Unavailable in NASM haven't been fixed yet as these seem to be valid instructions by the AMD manual.

**Comment by astocko** [comment]
There's a few more AMD only instructions. We could look into optional CPU feature checking in the runtime.

|            |            |           |           | 
|------------|------------|-----------|-----------| 
| MOVNTSS    | MOVNTSD    |           |           | 
|            |            |           |           | 
| VPPERM     |            |           |           | 
| VPCMOV     |            |           |           | 
|            |            |           |           | 
| VPROTB     | VPROTW     | VPROTD    | VPROTQ    | 
| VPSHAB     | VPSHAW     | VPSHAD    | VPSHAQ    | 
| VPSHLB     | VPSHLW     | VPSHLD    | VPSHLQ    | 
| VPCOMB     | VPCOMW     | VPCOMD    | VPCOMQ    | 
| VPCOMUB    | VPCOMUW    | VPCOMUD   | VPCOMUQ   | 
|            |            |           |           | 
| VPHADDBW   | VPHADDBD   | VPHADDBQ  |           | 
| VPHADDWD   | VPHADDWQ   |           |           | 
| VPHADDDQ   |            |           |           | 
| VPHADDUBW  | VPHADDUBD  | VPHADDUBQ |           | 
| VPHADDUWD  | VPHADDUWQ  |           |           | 
| VPHADDUDQ  |            |           |           | 
|            |            |           |           | 
| VPHSUBBW   | VPHSUBWD   | VPHSUBDQ  |           | 
|            |            |           |           | 
| VPMACSDQH  | VPMACSDQL  |           |           | 
| VPMACSDD   | VPMACSWD   | VPMACSWW  | VPMADCSWD | 
|            |            |           |           | 
| VPMACSSDD  |            |           |           | 
| VPMACSSDQH | VPMACSSDQL |           |           | 
| VPMACSSWD  | VPMACSSWW  |           |           | 
| VPMADCSSWD |            |           |           | 
|            |            |           |           | 
| VFRCZSS    | VFRCZSD    | VFRCZPS   | VFRCZPD   | 
|            |            |           |           | 
| VPERMIL2PD |            |           |           | 
| VPERMIL2PS |            |           |           |

**Comment by astocko** [comment]
I'm submitting a PR today addressing the majority of these issues. The encoding table is now generated from LLVM definitions. Documentation and notes are forthcoming.

**Comment by astocko** [comment]
Generated opmap along with single instruction encoding tests have been committed to the opmap branch.
