### ISSUE TITLE
Build failed with fresh rustc.

### ISSUE THREAD

**Issue by singaraiona** [CensoredUsername/dynasm-rs#19]
`error[E0308]: mismatched types
  --> /data/work/dynasm-rs/plugin/src/lib.rs:83:46
   |
83 |     let token_tree = ecx.expander().fold_tts(token_tree);
   |                                              ^^^^^^^^^^ expected struct `syntax::tokenstream::TokenStream`, found reference
   |
   = note: expected type `syntax::tokenstream::TokenStream`
              found type `&[syntax::tokenstream::TokenTree]`

error[E0308]: mismatched types
  --> /data/work/dynasm-rs/plugin/src/lib.rs:85:46
   |
85 |     let mut parser = ecx.new_parser_from_tts(&token_tree);
   |                                              ^^^^^^^^^^^ expected slice, found struct `syntax::tokenstream::TokenStream`
   |
   = note: expected type `&[syntax::tokenstream::TokenTree]`
              found type `&syntax::tokenstream::TokenStream`

error: aborting due to 2 previous errors

error: Could not compile `dynasm`.`

-----
rustc --version
rustc 1.17.0-nightly (6eb9960d3 2017-03-19)

**Comment by singaraiona** [comment]
`/// The guts of the dynasm! macro start here.
fn dynasm<'cx>(ecx: &'cx mut ExtCtxt,
               span: Span,
               token_tree: &[TokenTree])
               -> Box<MacResult + 'cx> {
    // expand all macros in our token tree first. This enables the use of rust macros
    // within dynasm (whenever this actually gets implemented within rustc)
    let mut parser = ecx.new_parser_from_tts(token_tree);

    // due to the structure of directives / assembly, we have to evaluate while parsing as
    // things like aliases, arch choices, affect the way in which parsing works.

    match compile(ecx, &mut parser) {
        Ok(stmts) => {
            Box::new(DynAsm {
                         ecx: ecx,
                         stmts: stmts,
                     })
        }
        Err(mut e) => {
            e.emit();
            DummyResult::any(span)
        }
    }
}`

seems line `let token_tree = ecx.expander().fold_tts(token_tree);` doesn't need anymore

**Comment by CensoredUsername** [comment]
this apparently never got closed back then, closing it now as it builds fine.
