### ISSUE TITLE
mov r64, imm64 seems to be unsupported

### ISSUE THREAD

**Issue by Vurich** [CensoredUsername/dynasm-rs#40]
In 64-bit mode, one would expect the immediate argument to `mov r64, ...` to be `imm64`, but it appears to be `imm32`. There is apparently no efficient way to set a register to a 64-bit value. AFAICT Rust's `asm!` macro supports this fine.

The `movabs` extension is supported with a 64-bit immediate operand but only if the destination is rax.

**Comment by CensoredUsername** [comment]
`mov reg, QWORD imm` should generate a 64-bit immediate move instruction.

Note that `movabs` does something different from what you think it does in dynasm. It is the instruction that implements a 64-bit displacement memory operation.

**Comment by Vurich** [comment]
Thank you for the help. I can't find information on what `movabs` in dynasm refers to, do you have a link to some docs? All I can find is the references to AT&T using it as a convention to specify `mov r64, imm64`.

**Comment by CensoredUsername** [comment]
It's listed in the [main page of the documentation](https://censoredusername.github.io/dynasm-rs/language/index.html): `LuaJIT uses the mov64 mnemnonic to encode 64-bit displacement mov. Dynasm-rs uses the movabs mnemnonic with a 64-bit immediate parameter to encode this.`

**Comment by Vurich** [comment]
Right, but I don't really know what that means (or rather, it seems like `mov64` does `mov r64, imm64`, which is what I thought it did). When you say "64-bit displacement mov" do you mean `mov` with a 64-bit immediate component of the address?

**Comment by CensoredUsername** [comment]
It does the equivalent of `mov [QWORD 0x1122334455667788], rax` and `mov rax, [QWORD 0x1122334455667788]` but as only the large displacement can be encoded without any index/base registers we forego displacement notation for it currently (I didn't want to add a full additional addressing mode for a single instruction).
