### ISSUE TITLE
Broken on latest nightly

### ISSUE THREAD

**Issue by Vurich** [CensoredUsername/dynasm-rs#41]
On the latest nightly (1.35) the following error is thrown by the compiler:

```
error[E0308]: mismatched types
  --> /home/jef/.cargo/registry/src/github.com-1ecc6299db9ec823/dynasm-0.2.3/src/lib.rs:51:64
   |
51 |                                       allow_internal_unstable: false,
   |                                                                ^^^^^ expected enum `std::option::Option`, found bool
   |
   = note: expected type `std::option::Option<std::rc::Rc<[syntax::ast::Symbol]>>`
              found type `bool`
```

This has been broken since at least March 1st, but works with the nightly from February 1st.

**Comment by CensoredUsername** [comment]
You're currently using dynasm v0.2.3, but the most recent version is dynasm v0.3.2 (which switched from being a plugin to a proc-macro to avoid these issues).

Is there a reason you cannot use v0.3.2?

**Comment by Vurich** [comment]
Nope, there’s no issue there. Sorry, my mistake, I did `cargo update` but didn’t take into account the possibility that the major had bumped because I carried on working on the older nightly instead of continuing to try to fix this problem. I’ll move to 3.x in the morning.
