### ISSUE TITLE
Example/Tutorial inaccurate?

### ISSUE THREAD

**Issue by ptersilie** [CensoredUsername/dynasm-rs#43]
Trying to follow the tutorial/example, I was getting the following error:
```
error: dynasmtest/target/debug/deps/libdynasm-c463bfe8527c932a.so: undefined symbol: __rustc_plugin_registrar_aa7442ab6739c353d00149a1c4ce6dd__
 --> src/main.rs:2:11
  |
2 | #![plugin(dynasm)]
  |           ^^^^^^
```
In order to get dynasm-rs working I had to change the imports as follows:
```rust
#![feature(proc_macro_hygiene)]
extern crate dynasmrt;
#[macro_use]
extern crate dynasm;
```

I'm not sure if this an issue with my setup or whether this is due to dynasm-rs transitioning from a compiler plugin to proc macros, and the tutorial just hasn't been updated yet.

**Comment by CensoredUsername** [comment]
That's definitely an issue with the tutorial where it hasn't been updated yet to reflect the proc-macro nature of the crate after v4.0.0. I'll bring it up to date soon. Sorry by the way that I missed your message on IRC.

**Comment by CensoredUsername** [comment]
The actual examples in the doc/examples folder are properly updated if you need more reference material.

**Comment by ptersilie** [comment]
No worries. I got there in the end. I must have missed the doc/examples folder, as that would have saved me some trial and error. ;-)

**Comment by CensoredUsername** [comment]
I've updated the tutorial ;-)
