### ISSUE TITLE
No constructor for `VecAssembler`

### ISSUE THREAD

**Issue by Recmo** [CensoredUsername/dynasm-rs#45]
The `VecAssembler` is part of the public interface, but there doesn't seem to be a way to construct or obtain one.

**Comment by CensoredUsername** [comment]
Whoops, I'll fix that.

**Comment by CensoredUsername** [comment]
I've made some changes on the dev branch, could you check that they fulfill your requirements?

**Comment by CensoredUsername** [comment]
@Recmo have you had time to look at this?

**Comment by CensoredUsername** [comment]
This should be resolved by v0.6.0.
