### ISSUE TITLE
Broken link to the documentation

### ISSUE THREAD

**Issue by nlinker** [CensoredUsername/dynasm-rs#56]
Hi!

Let me file a (minor) bug.

In the README file there is the link to the documentation, that responds with 404 currently:
```
## Documentation

[Documentation](https://CensoredUsername.github.com/dynasm-rs/language/index.html).
```

Expected result: the link should open the documentation.

**Comment by CensoredUsername** [comment]
Ah, github phased out .github.com subdomains in favour of .github.io subdomains. Will fix, thanks for the report!

**Comment by CensoredUsername** [comment]
Fixed!
