### ISSUE TITLE
x86 support

### ISSUE THREAD

**Issue by CensoredUsername** [CensoredUsername/dynasm-rs#6]
Currently only long mode is supported, while it should be possible to also support protected mode with modifications to the encoding infrastructure

**Comment by CensoredUsername** [comment]
One of the big problems with this currently is that the runtime relies on generating position-independent code. (If necessary it will allocate a larger buffer and copy everything over in there). This means that, when labels are used as memory displacements, these displacements will have to be relocated every time the buffer is swapped.

**Comment by brunoczim** [comment]
Is the project still on?

**Comment by CensoredUsername** [comment]
I still want to finish it, but I'm currently waiting to see what gets stabilized as the new procedural macro system as I don't want to have to rewrite even more code.

**Comment by darfink** [comment]
Just wanted to explicitly express my interest in x86 support as well, I'm confined to it due to my target environment.

**Comment by CensoredUsername** [comment]
Guess I'll note down here what will be necessary for x86 support here for now so people can have an overview of what still is necessary for x86 support,

- [ ] Parsing changes: adapt the x64 parser to also support x86 by adding a mode which changes the set of accepted registers and the implicit sizes of several registers (debug/control registers).
- [ ] Validation changes: In x86-mode, disallow x64-only functionality.
- [ ] Instruction data changes: Add some flags for instruction variants only supported in x86 mode.
- [ ] Runtime changes: The absence of RIP-relative memory references in favor of absolute 32-bit addresses means that the x86 assembler will require a very different relocation model. Notably, it will be necessary to reprocess all offsets in the case where the backing executable memory buffer gets reallocated. 
- [ ] Encoding changes: Add support for the new instruction data flags and change the way RIP-relative memory references get encoded (as absolute addresses that get relocated)

**Comment by CensoredUsername** [comment]
As it seems expression and statement-type procedural macros are not going to be stabilized anytime soon, I've decided to just start working on x86 support with the current parsing/codegen backend instead of waiting for anything to get stabilized.

Runtime support has been implemented, and I'm currently working on the required plugin changes.

**Comment by CensoredUsername** [comment]
With the release of v0.2.0, x86 support has landed!

**Comment by darfink** [comment]
Awesome to hear!
