### ISSUE TITLE
Address to label

### ISSUE THREAD

**Issue by djwatson** [CensoredUsername/dynasm-rs#86]
Is it possible to take the address of a label?  Something like:

```rust
dynasm!(code
      ; .qword [->label offset_tag]
);
```

I'm trying to accomplish tagged-pointer constants, something like this in C:

```c
struct foo {
  long other;
}

#define TAG 1
struct foo bar1;
struct foo bar2 = {.other = (long)&bar1 + TAG};
```

This needs a relocation depending on where bar1/bar2 end up in the code stream, but it's unclear how I get the absolute address of a global label.   LitPool doesn't look like it has a sufficient interface to do this either.

Thanks

**Comment by CensoredUsername** [comment]
You can query the location of a previously defined label via `Assembler::labels()` which returns a [`LabelRegistry`](https://censoredusername.github.io/dynasm-rs/dynasmrt/components/struct.LabelRegistry.html). From that you can use `LabelRegistry::resolve_static(StaticLabel::Global("yourlabel"))` to get the offset of that label location into the assembling buffer. The absolute address of the label is then the base address of the assembling buffer plus the label offset.

This of course only works if the global label has already been defined in the code before calling this method. And it'll go stale if the buffer needs to be relocated. 

Right now there's indeed no support for putting the absolute label address directly in the code stream, especially if such a label is only defined afterwards. Such a feature would also need to use proper relocations if the assembling buffer needed to be moved or resized. Likely the best way to handle this is some kind of directive. But even then it'd be tricky with tagged pointers. I _think_ it could work as long as the tags are simply added to the pointer as relocating them is essentially current_value - old_base_address + new_base_address.

**Comment by djwatson** [comment]
Thanks for the quick feedback!

> Right now there's indeed no support for putting the absolute label address directly in the code stream ... Such a feature would also need to use proper relocations if the assembling buffer needed to be moved or resized

Yes, that's what I was looking for, basically the same way nasm/llvm ir etc would do it.  Your relocation math would work fine.  I wasn't quite sure if it was implemented or not, since I did see various relocation types like RelToAbs in the code.  I'll find another way to do what I need, thanks again.

```asm
foo:
	mov rax, bar + 1
bar:
	dq $10

nasm -f elf64 test.s

0000000000000000 <foo>:
   0:	48 b8 00 00 00 00 00 	movabs $0x0,%rax
   7:	00 00 00

readelf -r test.o

Relocation section '.rela.text' at offset 0x2a0 contains 1 entry:
  Offset          Info           Type           Sym. Value    Sym. Name + Addend
000000000002  000200000001 R_X86_64_64       0000000000000000 .text + b

```
