### ISSUE TITLE
Support of int 0x80

### ISSUE THREAD

**Issue by hallucino** [CensoredUsername/dynasm-rs#99]
Do you think it could make sense to switch:
int imm8

to 

int imm16 

It will allow to support some case like for i386:
int 0x80

**Comment by CensoredUsername** [comment]
Does that currently not work then? You might need to explicitly state `int 0x80u8 as _` because the x86 backend assumes signed immediates.

**Comment by hallucino** [comment]
ah damned yes sorry ! thx for the reply
